# Generated by Django 5.1.6 on 2025-03-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
